<div class="vapeCalc">
    <div class="ohmCalculator">
        <span class="ohmLaws">
            <div class="error-explainer"><h3>(X) Must Be A Number</h3><p>Please clear field or change to a proper number</p></div>
            <label>VOLTS : </label>
            <input  type="text" maxlength="4" name="volts" id="volts" value="0.0">
            <button data-field="volts" type="reset" class="action submit primary calcReset">Clear</button>
        </span>
        <span class="ohmLaws">
            <div class="error-explainer"><h3>(X) Must Be A Number</h3><p>Please clear field or change to a proper number</p></div>
            <label>OHMS  : </label>
            <input type="text" maxlength="4" name="ohms"  id="ohms" value="0.0">
            <button data-field="ohms" type="reset" class="action submit primary calcReset">Clear</button>
        </span>
        <span class="ohmLaws">
            <div class="error-explainer"><h3>(X) Must Be A Number</h3><p>Please clear field or change to a proper number</p></div>
            <label>AMPS  : </label>
            <input type="text" maxlength="4" name="amps"  id="amps" value="0.0">
            <button data-field="amps" type="reset" class="action submit primary calcReset">Clear</button>
        </span>
        <span class="ohmLaws">
            <div class="error-explainer"><h3>(X) Must Be A Number</h3><p>Please clear field or change to a proper number</p></div>
            <label>WATTS : </label>
            <input type="text" maxlength="4" name="watts" id="watts" value="0.0">
            <button data-field="watts" type="reset" class="action submit primary calcReset">Clear</button>
        </span>
            <div class="primary" id="primaryButton">
                <button  type="submit" class="action submit primary" title="<?php echo __('Submit') ?>">
                    <span><?php echo __('Submit') ?></span>
                </button>
            </div>
    </div>
    <div class="wireCalc">
        Ohms  : <input type="text" maxlength="4" name="ohms" value="0.0"><br>
        <select name="material" id="material">
            <option value="Kanthal">Kanthal</option>
            <option value="Stainless Steel">Stainless Steel</option>
            <option value="Titanium">Titanium</option>
            <option value=""></option>
        </select>
    </div>
    <div class="wireRecomendor">
        <div class="preview">
            Preview Image
        </div>
        <div class="recmendedItems">
            Recomended Products
        </div>
    </div>
</div>

<script type="application/x-javascript">
    require(['jquery'], function($){main($ , "<?php echo $block->ajaxUrl(); ?>");})
</script>